"""initial schema

Revision ID: 3257f60ee6a4
Revises:
Created: 2026-08-03 18:46:56.118424

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

#: Tables holding customer data, each of which gets a tenant-isolation policy.
#: Mirrors `rag.db.models.TENANT_SCOPED_TABLES`; duplicated rather than imported
#: because a migration must describe the schema *as of this revision*. Importing
#: from application code makes old migrations change meaning when models evolve,
#: which is how a replayed migration history stops reproducing the database.
TENANT_SCOPED_TABLES: tuple[str, ...] = (
    "users",
    "groups",
    "group_members",
    "collections",
    "documents",
    "document_permissions",
    "chunks",
)

#: Native ENUM types introduced by this revision. Postgres keeps them after the
#: owning tables are dropped, so `downgrade()` must remove them explicitly.
ENUM_TYPES: tuple[str, ...] = (
    "document_status",
    "job_kind",
    "job_status",
    "principal_type",
    "tenant_status",
    "user_role",
    "user_status",
)

revision: str = "3257f60ee6a4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "suspended", "deleted", name="tenant_status"),
            nullable=False,
        ),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenants_slug")),
    )
    op.create_table(
        "collections",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_collections_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collections")),
        sa.UniqueConstraint("tenant_id", "slug", name="uq_collections_tenant_id_slug"),
    )
    op.create_index(op.f("ix_collections_tenant_id"), "collections", ["tenant_id"], unique=False)
    op.create_table(
        "groups",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_groups_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_groups")),
        sa.UniqueConstraint("tenant_id", "slug", name="uq_groups_tenant_id_slug"),
    )
    op.create_index(op.f("ix_groups_tenant_id"), "groups", ["tenant_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column(
            "kind",
            sa.Enum("ingest_document", "reindex_document", "delete_document", name="job_kind"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "succeeded", "failed", "cancelled", name="job_status"),
            nullable=False,
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default=sa.text("5"), nullable=False),
        sa.Column(
            "run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_jobs_attempts_non_negative")),
        sa.CheckConstraint("max_attempts >= 1", name=op.f("ck_jobs_max_attempts_positive")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_jobs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(
        "ix_jobs_claimable",
        "jobs",
        ["priority", "run_after"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(
        "ix_jobs_running_locked_at",
        "jobs",
        ["locked_at"],
        unique=False,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_index(op.f("ix_jobs_tenant_id"), "jobs", ["tenant_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=255), server_default=sa.text("''"), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "role", sa.Enum("owner", "admin", "member", "viewer", name="user_role"), nullable=False
        ),
        sa.Column(
            "status", sa.Enum("active", "invited", "disabled", name="user_status"), nullable=False
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_users_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("tenant_id", "email", name="uq_users_tenant_id_email"),
    )
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "queued",
                "parsing",
                "chunking",
                "embedding",
                "indexing",
                "ready",
                "failed",
                "reindexing",
                "deleting",
                "deleted",
                name="document_status",
            ),
            nullable=False,
        ),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "acl_principals",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_documents_size_bytes_non_negative")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_documents_version_positive")),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_documents_collection_id_collections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_documents_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("fk_documents_uploaded_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint(
            "tenant_id", "content_hash", name="uq_documents_tenant_id_content_hash"
        ),
    )
    op.create_index(
        "ix_documents_acl_principals",
        "documents",
        ["acl_principals"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("ix_documents_collection_id", "documents", ["collection_id"], unique=False)
    op.create_index(op.f("ix_documents_tenant_id"), "documents", ["tenant_id"], unique=False)
    op.create_index(
        "ix_documents_tenant_id_status", "documents", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "group_members",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_group_members_group_id_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_group_members_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_group_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id", name=op.f("pk_group_members")),
    )
    op.create_index("ix_group_members_user_id", "group_members", ["user_id"], unique=False)
    op.create_table(
        "chunks",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("char_start", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("char_end", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("embedding_model", sa.String(length=128), nullable=True),
        sa.Column("embedding_version", sa.String(length=64), nullable=True),
        sa.Column(
            "acl_principals",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("char_end >= char_start", name=op.f("ck_chunks_char_range_ordered")),
        sa.CheckConstraint("ordinal >= 0", name=op.f("ck_chunks_ordinal_non_negative")),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_chunks_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_chunks_document_id_ordinal"),
    )
    op.create_index(
        "ix_chunks_acl_principals",
        "chunks",
        ["acl_principals"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("ix_chunks_document_id", "chunks", ["document_id"], unique=False)
    op.create_index(
        "ix_chunks_embedding_model", "chunks", ["tenant_id", "embedding_model"], unique=False
    )
    op.create_index(op.f("ix_chunks_tenant_id"), "chunks", ["tenant_id"], unique=False)
    op.create_table(
        "document_permissions",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column(
            "principal_type",
            sa.Enum("user", "group", "role", "tenant", name="principal_type"),
            nullable=False,
        ),
        sa.Column("principal_id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_permissions_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
            name=op.f("fk_document_permissions_granted_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_document_permissions_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "document_id", "principal_type", "principal_id", name=op.f("pk_document_permissions")
        ),
    )
    op.create_index(
        "ix_document_permissions_principal",
        "document_permissions",
        ["tenant_id", "principal_type", "principal_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    _enable_row_level_security()


def _enable_row_level_security() -> None:
    """Make the database, not the application, the enforcer of tenant isolation.

    Autogenerate cannot produce any of this — it compares table structure, and
    policies are not structure. Hand-written on purpose.

    Three details decide whether this is real security or decoration:

    1. ``FORCE ROW LEVEL SECURITY``. Table *owners* bypass RLS by default, and
       the application connects as the role that owns these tables. Without
       FORCE, every policy below is silently inert. This is the single most
       common way RLS ends up doing nothing.

    2. ``NULLIF(current_setting('rag.tenant_id', true), '')``. The ``true``
       argument means "missing_ok" — an unbound setting yields NULL rather than
       raising. NULLIF additionally maps the empty string (how we *clear* the
       scope) to NULL. Since ``tenant_id = NULL`` evaluates to NULL, an unscoped
       session matches nothing. **Forgetting to scope returns zero rows, never
       every row** — the fail-closed property that justified RLS over
       application-side filtering alone.

    3. ``WITH CHECK`` as well as ``USING``. USING governs what a statement may
       *read*; WITH CHECK governs what it may *write*. With USING alone, a
       session scoped to tenant A could still INSERT a row stamped tenant B —
       invisible to A afterwards, and quietly corrupting B's data.

    ``jobs`` is deliberately absent: workers poll across tenants by design and
    then scope themselves per claimed job. No HTTP endpoint exposes that table.
    """
    predicate = "tenant_id = NULLIF(current_setting('rag.tenant_id', true), '')::uuid"

    for table in TENANT_SCOPED_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({predicate}) WITH CHECK ({predicate})"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_document_permissions_principal", table_name="document_permissions")
    op.drop_table("document_permissions")
    op.drop_index(op.f("ix_chunks_tenant_id"), table_name="chunks")
    op.drop_index("ix_chunks_embedding_model", table_name="chunks")
    op.drop_index("ix_chunks_document_id", table_name="chunks")
    op.drop_index("ix_chunks_acl_principals", table_name="chunks", postgresql_using="gin")
    op.drop_table("chunks")
    op.drop_index("ix_group_members_user_id", table_name="group_members")
    op.drop_table("group_members")
    op.drop_index("ix_documents_tenant_id_status", table_name="documents")
    op.drop_index(op.f("ix_documents_tenant_id"), table_name="documents")
    op.drop_index("ix_documents_collection_id", table_name="documents")
    op.drop_index("ix_documents_acl_principals", table_name="documents", postgresql_using="gin")
    op.drop_table("documents")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_jobs_tenant_id"), table_name="jobs")
    op.drop_index(
        "ix_jobs_running_locked_at",
        table_name="jobs",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_index(
        "ix_jobs_claimable", table_name="jobs", postgresql_where=sa.text("status = 'queued'")
    )
    op.drop_table("jobs")
    op.drop_index(op.f("ix_groups_tenant_id"), table_name="groups")
    op.drop_table("groups")
    op.drop_index(op.f("ix_collections_tenant_id"), table_name="collections")
    op.drop_table("collections")
    op.drop_table("tenants")
    # ### end Alembic commands ###

    _drop_enum_types()


def _drop_enum_types() -> None:
    """Drop the native ENUM types that table creation implicitly created.

    Autogenerate emits `op.drop_table(...)` but never drops these. SQLAlchemy
    creates a Postgres ENUM as a *side effect* of the first column that uses it,
    and Alembic does not track that side effect — so the types outlive the
    downgrade, and the next upgrade dies with:

        DuplicateObjectError: type "tenant_status" already exists

    Caught by an explicit `downgrade base` / `upgrade head` round trip, which is
    now a CI step. A migration you cannot replay is not a migration, it is a
    one-way script — and it means a restored-from-scratch database and a
    migrated one are not guaranteed to match.

    `IF EXISTS` so a partial downgrade can still be re-run.
    """
    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
